Update root README
AndroidEngineers/7-day-Android-App-Challenge pull request #21
Opened 2024-08-27 08:18 UTC by sachinsinghd11

# Pull Request
update root README
## Description

Please include a summary of the changes you have made. Highlight the key aspects of your project.
Includes project information in root README
## Checklist

- [x] My project includes a `README.md` file with a brief overview of the project, how to set it up, and any relevant information.
- [x] I have added a screenshot or screen recording showing the functionality of the app.
- [x] I have tested the project and confirmed it works as expected.

## Screenshots

<p>
   <img src="https://github.com/abhinavcodedev/7-day-Android-App-Challenge/blob/main/AniFetch/screenshots/SplashScreen.png" width="200" height="400" />
  <img src="https://github.com/abhinavcodedev/7-day-Android-App-Challenge/blob/main/AniFetch/screenshots/Screenshot1.png" width="200" height="400" />
  <img src="https://github.com/abhinavcodedev/7-day-Android-App-Challenge/blob/main/AniFetch/screenshots/Screenshot2.png" width="200" height="400" />
</p>

## Project README

Please ensure that your project's `README.md` is detailed and includes:

- A brief introduction to the project.
- Installation steps.
- Key features.
- Any additional instructions or information.

## Additional Notes

Is there anything else the maintainers should know about your contribution?

---

Thank you for your contribution!

2024-08-27 10:23 UTC, anandwana001 requested changes

2024-08-27 10:23 UTC, anandwana001 commented on README.md
> +| Recipe Roulette | [Sachin Singh Dighan](@sachinsinghd11) | <img src="https://github.com/user-attachments/assets/e2354ad1-1fbd-424e-88a4-abe7fbbedccc" width="125" height="125" /><br><img src="https:
looks like you had overwritten the data.

2024-08-28 08:34 UTC, sachinsinghd11 commented on README.md
> +| Recipe Roulette | [Sachin Singh Dighan](@sachinsinghd11) | <img src="https://github.com/user-attachments/assets/e2354ad1-1fbd-424e-88a4-abe7fbbedccc" width="125" height="125" /><br><img src="https:
@anandwana001  resolved the PR comment, please check

2024-08-28 10:48 UTC, anandwana001 approved these changes

2024-08-28 10:48 UTC, merged