ui changes
AndroidEngineers/7-day-Android-App-Challenge pull request #33
Opened 2024-10-03 13:52 UTC by JuileeBhombe

# Pull Request

## Description

Recipe Screen and Recipe Details Screen UI

2024-10-03 14:18 UTC, anandwana001 requested changes
Can we add screenshots?

2024-10-03 14:18 UTC, anandwana001 commented on JuileeBhombe/RecipeRoulette/app/src/main/java/com/juileebhombe/reciperoulette/ui/screens/RecipesScreen.kt
> +fun RecipesTab() {
fun can be private?

2024-10-03 14:18 UTC, anandwana001 commented on JuileeBhombe/RecipeRoulette/app/src/main/java/com/juileebhombe/reciperoulette/ui/screens/RecipesScreen.kt
> +            letterSpacing = (1).sp,
any specific reason for brackets? `(1).sp`

2024-10-03 14:18 UTC, anandwana001 commented on JuileeBhombe/RecipeRoulette/app/src/main/java/com/juileebhombe/reciperoulette/ui/screens/RecipeDetails.kt
> +    Column(Modifier.verticalScroll(rememberScrollState())) {
this vs LazyColumn?
any rational for this?

2024-10-04 04:00 UTC, JuileeBhombe commented
> Can we add screenshots?

I am not able to upload screenshots in current PR.

2024-10-04 04:04 UTC, JuileeBhombe commented on JuileeBhombe/RecipeRoulette/app/src/main/java/com/juileebhombe/reciperoulette/ui/screens/RecipesScreen.kt
> +fun RecipesTab() {
Resolved

2024-10-04 04:04 UTC, JuileeBhombe commented on JuileeBhombe/RecipeRoulette/app/src/main/java/com/juileebhombe/reciperoulette/ui/screens/RecipesScreen.kt
> +            letterSpacing = (1).sp,
Resolved

2024-10-04 04:15 UTC, JuileeBhombe commented on JuileeBhombe/RecipeRoulette/app/src/main/java/com/juileebhombe/reciperoulette/ui/screens/RecipeDetails.kt
> +    Column(Modifier.verticalScroll(rememberScrollState())) {
Resolved

2024-10-04 04:52 UTC, anandwana001 approved these changes

2024-10-04 04:52 UTC, merged