UI of AniFetch
AndroidEngineers/7-day-Android-App-Challenge pull request #7
Opened 2024-08-21 09:36 UTC by abhinavcodedev

# Pull Request

## Description

Please include a summary of the changes you have made. Highlight the key aspects of your project.

## Checklist

- [ ] My project includes a `README.md` file with a brief overview of the project, how to set it up, and any relevant information.
- [ ] I have added a screenshot or screen recording showing the functionality of the app.
- [ ] I have tested the project and confirmed it works as expected.

## Screenshots

If applicable, please add a screenshot or a screen recording to demonstrate the functionality of your app.

## Project README

Please ensure that your project's `README.md` is detailed and includes:

- A brief introduction to the project.
- Installation steps.
- Key features.
- Any additional instructions or information.

## Additional Notes

Is there anything else the maintainers should know about your contribution?

---

Thank you for your contribution!

2024-08-21 10:11 UTC, anandwana001 requested changes
Currently, we are reviewing and accpeting ony day 1 task

2024-08-21 10:11 UTC, anandwana001 commented on AniFetch/Screenshot_20240821_143126.png
can we add screenshot to pr descritpion as well?

2024-08-21 10:11 UTC, anandwana001 commented on AniFetch/app/src/main/java/com/example/anifetch/APIServices.kt
> +    @GET("anime")
not a day 1 task

2024-08-21 14:40 UTC, abhinavcodedev commented on AniFetch/app/src/main/java/com/example/anifetch/APIServices.kt
> +    @GET("anime")
So can I remove the API service from my code and than use local storage. First I check with local storage then I use API

2024-08-22 02:26 UTC, anandwana001 commented
@abhinavcodedev update PR description with all the details

2024-08-22 02:28 UTC, anandwana001 requested changes
For Now, I am reviewing only UI part as part of Day 1 task.

Please clean the UI Code.

2024-08-22 02:28 UTC, anandwana001 commented on AniFetch/app/src/main/java/com/example/anifetch/MainActivity.kt
> +                }
should be in a separate file

2024-08-22 02:28 UTC, anandwana001 commented on AniFetch/app/src/main/java/com/example/anifetch/MainActivity.kt
> +fun MainScreen(navController: NavHostController) {
separate file

2024-08-22 02:28 UTC, anandwana001 commented on AniFetch/app/src/main/java/com/example/anifetch/MainActivity.kt
> +            //Basic Text Field for search input
why comment code in PR?

2024-08-23 13:01 UTC, abhinavcodedev commented
@anandwana001  I've addressed the requested changes. Please review when you get a chance.

2024-08-24 15:02 UTC, anandwana001 approved these changes

2024-08-24 15:02 UTC, merged